### ISSUE TITLE
update `salesforce` jobs to use `bulkQuery`

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/gife#12]
### Summary
A new helper function for querying records in bulk is now available of salesforce adaptor `v4.2.0`.

Update `jobs/getDeletedCampaignMembers.js` and `jobs/getCampaignMembers.js` to use the new `bulkQuery` function. and remove the `offset` query. 

Important thing to note, the result of the `bulkQuery()` function will be in `state.data` not in `state.references`
So you have to update   `const campaignMembers = state.references.map(ref => ref.records).flat();` to use `  const campaignMembers = state.data;`

**Comment by aleksa-krolls** [comment]
@bryceVeraSolutions as @mtuchi flagged on Slack - please hold working on this issue until we cut a new Adaptor release on Monday

**Comment by mtuchi** [comment]
@bryceVeraSolutions new version of salesforce adaptor is available now, `@openfn/language-salesforce@4.2.1`
You can proceed now with implementation. 

You can clean the existing adaptors version by running `openfn repo clean` first before running `openfn workflow.json -i -o tmp/output.json`

**Comment by mtuchi** [comment]
Hiya @bryceVeraSolutions , sorry i forgotten to mention a crucial details about the `bulkQuery`. You need to specify `apiVersion: "59.0"` in your salesforce credentials

**Comment by mtuchi** [comment]
**[Regarding `bulkQuery()` function failing for aggregate queries](https://github.com/OpenFn/adaptors/issues/395)** 
It doesn't seem to be the issue with the adaptor function, rather it's limitation with [Bulk API 2.0](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/query_create_job.htm) It has a limitation on **Parent-to-child [relationship queries](https://developer.salesforce.com/docs/atlas.en-us.246.0.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_relationships_understanding.htm). (Child-to-parent relationship queries are supported.)**
cc @bryceVeraSolutions

**Comment by mtuchi** [comment]
First workflow is done on this PR https://github.com/OpenFn/gife/pull/13 
Thanks @bryceVeraSolutions
