### ISSUE TITLE
The Remove Deleted Members Tags job is failing with an Adaptor error

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/gife#21]
The current scenario is as follows ([log](https://app.openfn.org/projects/f07240d8-8bb7-4cff-9e20-cc8d8059892f/runs/0a3d4f28-812c-429e-967c-45a3fabf4898?step=28658550-7fae-4beb-917c-d1ed20497af7)):

Mailchimp returns a 200, so the connection is successful (Mailchimp API documentation: [batch-subscribe-or-unsubscribe](https://mailchimp.com/developer/marketing/api/lists/batch-subscribe-or-unsubscribe/)).
However, we're having an AdaptorError, and we're not sure how to fix it. Could you guys save the day again and help us? :blob_help:

```
ADA Mailchimp says 200
R/T Operation 1 complete in 408ms
R/T Starting operation 2
R/T Removed configuration from final state
R/T Failed step Remove deleted members tags after 643ms
R/T {
  "details": {},
  "message": "[\n  []\n]",
  "name": "AdaptorError",
  "severity": "fail",
  "source": "runtime"
}
R/T Check state.errors.d839d64f-78f7-4178-ab9d-482bbedd8866 for details.
R/T Run complete with status: fail
```

Outcome: even when there are members to update (i.e., tags to be removed by updating Contact on Mailchimp using the active Campaing Memebers on Salesforce), the tags are not being removed from Mailchimp:
![Image](https://github.com/user-attachments/assets/5943662d-6f39-49b8-b0bc-deb54700d1a4)

Here is the [Run Log](https://app.openfn.org/projects/f07240d8-8bb7-4cff-9e20-cc8d8059892f/runs/0a3d4f28-812c-429e-967c-45a3fabf4898?step=28658550-7fae-4beb-917c-d1ed20497af7) of the [job](https://app.openfn.org/projects/f07240d8-8bb7-4cff-9e20-cc8d8059892f/w/273e2c2a-a97d-49eb-bebb-2dad0666a716?v=73) Remove deleted members Tags.

Adaptor:
mailchimp     0.7.1

Toggl
`Lightning Migration`

**Comment by mtuchi** [comment]
This was resolved from our call today with @williandeavila and shreya. The error was caused by throwing `null` values. 
I have also reconfigure GitHub sync
