### ISSUE TITLE
Improve chunk response errors in workflow-2

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/gife#8]
### Summary, 

Currently the workflow uses the batch subscribe or unsubscribe to delete member tags, This operation is performed in chunks of `500` records per request. The current implementation will only catch the last request response errors which is not ideally in a situation where you have more than one chunk. 

**Improve the workflow to handle chunk response errors**
See the implementation from the first workflow for inspiration 
-  https://github.com/OpenFn/gife/blob/main/jobs/getCampaignMembers.js#L56
- https://github.com/OpenFn/gife/blob/main/jobs/addOrUpdateMemberTags.js#L2-L28

**Comment by bryceVeraSolutions** [comment]
@mtuchi See https://github.com/OpenFn/gife/pull/9

**Comment by mtuchi** [comment]
> @mtuchi See #9
Closing this as it's done on #9
